<?php

/**
 * This is an autogenerated file. Do not edit this file manually.
 */

namespace Amanank\HalClient\Models\Discovered;

use Amanank\HalClient\Models\Model;

/**
 * {{propertiesDocs}}
 */
class {{className}} extends Model {

    protected $_endpoint = '{{endpoint}}';

    protected $fillable = [{{fillables}}];

    // Properties defined for type hinting and IDE autocompletion
    {{properties}}

    // Setter and Getter for data type enforcement
    {{enumSetters}}
    {{enumGetters}}

    // Relations
    {{relations}}

    // Search methods
    {{staticMethods}}

}
